openapi: 3.0.3
info:
  title: REST API Dutescu
  version: 1.0.0
  description: This doc will be used to find out things about my API
paths:
  /averagebrandemployees/:
    get:
      operationId: averagebrandemployees_retrieve
      tags:
      - averagebrandemployees
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /averageprodyear/:
    get:
      operationId: averageprodyear_retrieve
      tags:
      - averageprodyear
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /carbrands/:
    get:
      operationId: carbrands_retrieve
      tags:
      - carbrands
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: carbrands_create
      tags:
      - carbrands
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /carbrands/{name}:
    get:
      operationId: carbrands_retrieve_2
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - carbrands
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: carbrands_update
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - carbrands
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: carbrands_destroy
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - carbrands
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /cars/:
    get:
      operationId: cars_retrieve
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: cars_create
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /cars/{id}:
    get:
      operationId: cars_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: cars_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: cars_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /carstuned/:
    get:
      operationId: carstuned_retrieve
      tags:
      - carstuned
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: carstuned_create
      tags:
      - carstuned
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /carstuned/{id}:
    get:
      operationId: carstuned_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - carstuned
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: carstuned_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - carstuned
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: carstuned_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - carstuned
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /carworkshops/:
    get:
      operationId: carworkshops_retrieve
      tags:
      - carworkshops
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: carworkshops_create
      tags:
      - carworkshops
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /carworkshops/{id}:
    get:
      operationId: carworkshops_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - carworkshops
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: carworkshops_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - carworkshops
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: carworkshops_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - carworkshops
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /multiplecarbrand/:
    post:
      operationId: multiplecarbrand_create
      tags:
      - multiplecarbrand
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /owners/:
    get:
      operationId: owners_retrieve
      tags:
      - owners
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: owners_create
      tags:
      - owners
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /owners/{id}:
    get:
      operationId: owners_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - owners
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: owners_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - owners
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: owners_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - owners
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
