# Generated by Django 4.1.7 on 2023-03-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("A1HW", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
                ("Owner", models.CharField(max_length=200)),
                ("Founded", models.IntegerField(default=0)),
                ("Location", models.CharField(max_length=200)),
                ("NumberOfEmployees", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="CarsTunedBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CarID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CarID",
                        to="A1HW.car",
                    ),
                ),
                (
                    "CarWorkshopID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="WorkshopID",
                        to="A1HW.carworkshop",
                    ),
                ),
            ],
        ),
    ]
