# Generated by Django 4.1.7 on 2023-03-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("A1HW", "0002_carworkshop_carstunedby"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CarsTunedBy",
            new_name="CarTunedBy",
        ),
    ]
