# Generated by Django 4.1.7 on 2023-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A1HW", "0004_cartunedby_datetuned_cartunedby_tuningprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="ProductionYear",
            field=models.IntegerField(default=1),
        ),
    ]
